# Generated by Django 2.1.1 on 2018-11-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_announced', models.DateField()),
                ('news', models.CharField(max_length=300, verbose_name='News:')),
                ('name', models.CharField(max_length=50, verbose_name='Name:')),
                ('position', models.CharField(max_length=20, verbose_name='Position:')),
            ],
        ),
    ]
