# Generated by Django 2.1.1 on 2018-11-20 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aaronsapp', '0002_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.AddField(
            model_name='newspost',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/documents/'),
            preserve_default=False,
        ),
    ]
