# Generated by Django 2.1.1 on 2018-11-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaronsapp', '0003_auto_20181120_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='document',
            field=models.FileField(blank=True, upload_to='static/documents/'),
        ),
    ]
