# Generated by Django 2.1.1 on 2018-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaronsapp', '0007_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.CharField(max_length=30, verbose_name='Month Year:')),
                ('summary', models.CharField(max_length=300, verbose_name='Event Summary:')),
                ('leader', models.CharField(max_length=50, verbose_name='Event Organizer:')),
                ('mainstage', models.CharField(max_length=100, verbose_name='List all performers from the main stage:')),
                ('bunker', models.CharField(max_length=100, verbose_name='List all performers from the Deephouse Bunker:')),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
